# Generated by Django 2.2.2 on 2019-09-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('creator', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('url', models.TextField()),
                ('title0', models.CharField(blank=True, max_length=50, null=True)),
                ('detail0', models.CharField(blank=True, max_length=230, null=True)),
                ('callNumber0', models.CharField(blank=True, max_length=30, null=True)),
                ('title1', models.CharField(blank=True, max_length=50, null=True)),
                ('detail1', models.CharField(blank=True, max_length=230, null=True)),
                ('callNumber1', models.CharField(blank=True, max_length=30, null=True)),
                ('title2', models.CharField(blank=True, max_length=50, null=True)),
                ('detail2', models.CharField(blank=True, max_length=230, null=True)),
                ('callNumber2', models.CharField(blank=True, max_length=30, null=True)),
                ('title3', models.CharField(blank=True, max_length=50, null=True)),
                ('detail3', models.CharField(blank=True, max_length=230, null=True)),
                ('callNumber3', models.CharField(blank=True, max_length=30, null=True)),
                ('title4', models.CharField(blank=True, max_length=50, null=True)),
                ('detail4', models.CharField(blank=True, max_length=230, null=True)),
                ('callNumber4', models.CharField(blank=True, max_length=30, null=True)),
                ('title5', models.CharField(blank=True, max_length=50, null=True)),
                ('detail5', models.CharField(blank=True, max_length=230, null=True)),
                ('callNumber5', models.CharField(blank=True, max_length=30, null=True)),
                ('title6', models.CharField(blank=True, max_length=50, null=True)),
                ('detail6', models.CharField(blank=True, max_length=230, null=True)),
                ('callNumber6', models.CharField(blank=True, max_length=30, null=True)),
                ('title7', models.CharField(blank=True, max_length=50, null=True)),
                ('detail7', models.CharField(blank=True, max_length=230, null=True)),
                ('callNumber7', models.CharField(blank=True, max_length=30, null=True)),
                ('title8', models.CharField(blank=True, max_length=50, null=True)),
                ('detail8', models.CharField(blank=True, max_length=230, null=True)),
                ('callNumber8', models.CharField(blank=True, max_length=30, null=True)),
                ('title9', models.CharField(blank=True, max_length=50, null=True)),
                ('detail9', models.CharField(blank=True, max_length=230, null=True)),
                ('callNumber9', models.CharField(blank=True, max_length=30, null=True)),
                ('more', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('title', models.TextField()),
            ],
        ),
    ]
